### ISSUE TITLE
Domain name connection

### ISSUE THREAD

**Issue by vitkabele** [Thomaslegravier/SynologySwift#1]
Hi,
I'm looking to Your repository and I'm wondering whether is it possible to login to a Synology on a public IP using its domain name instead of the quickconnect id.

**Comment by Thomaslegravier** [comment]
Currently global login process try to resolve valid host based on your QuickConnect id. It’s usefull to let the login process do its job because it will find the best host option for a most fast/efficient communication with your Synology. For example, if your Synology is on your local network, it’s way more efficient to communicate through its local IP address.
If your prefer to use explict DDNS you can use the simple login process instead like this :

```swift
// Your quick id will not be used but is required for now (will be change in next release).
let dsInfos = SynologySwiftURLResolver.DSInfos(quickId: "your-quick-id", host: "your-ddns.synology.me", port: 5000)
SynologySwift.resolveLogin(dsInfos: dsInfos, sessionType: "DownloadStation", login: "your-login", password: "your-password") { (result) in
    switch result {
    case .success(let authInfos): print(authInfos)
    case .failure(let error): print(error)
    }
}
```

NB: global login process is also usefull to determine which service port to use (by default 5000). Then this port is required by the authentication process.


Don’t hesitate if your have any suggestion or idea. I will add futher features and improvements as soon as possible.

Regards

**Comment by vitkabele** [comment]
Great!
I was confused by the first argument `quickId`. I agree that it might be useful to let the login process determine its configuration from *QuickConnect*. Nevertheless this approach relies on the *QuickConnect* service and I think that the user should have the possibility to avoid using this.

Consider my setup: Synology NAS with public IPv4 and even IPv6 addresses both with A and AAAA DNS records. There is no need to rely on external cloud service to successfully connect.

Shortly: I think that it's great that there is an option to use *QuickConnect* but I also think that this should not be the only option.

**Comment by Thomaslegravier** [comment]
Thanks @vitkabele for your feedback. I will update interface soon ;)
